const CONFIG = {
  UNAUTHORIZED_MESSAGE: "Unauthorized",

  PATHAO_BASE_URL: "https://courier-api-sandbox.pathao.com",
  PATHAO_CLIENT_ID: "",
  PATHAO_CLIENT_SECRET: "",
  PATHAO_CLIENT_EMAIL: "",
  PATHAO_CLIENT_PASSWORD: "",
  PATHAO_GRANT_TYPE: "password",
  PATHAO_ALL_STORES_ENDPOINT: "/aladdin/api/v1/stores",
  PATHAO_CITY_LIST_ENDPOINT: "/aladdin/api/v1/city-list",
  PATHAO_PRICE_PLAN_ENDPOINT: "/aladdin/api/v1/merchant/price-plan",
  PATHAO_TOKEN_ENDPOINT: "/aladdin/api/v1/issue-token",
  PATHAO_ORDER_ENDPOINT: "/aladdin/api/v1/orders",
  PATHAO_CREATE_SHIPMENT_ENDPOINT: "/aladdin/api/v1/orders",
  PATHAO_CREATE_BULK_SHIPMENT_ENDPOINT: "/aladdin/api/v1/orders/bulk",

  ECOURIER_BASE_URL: "https://staging.ecourier.com.bd/api",
  ECOURIER_API_SECRET: "",
  ECOURIER_API_KEY: "",
  ECOURIER_USER_ID: "",
  ECOURIER_CREATE_SHIPMENT_ENDPOINT: "/order-place",
  ECOURIER_PACKAGE_LIST_ENDPOINT: "/packages",
  ECOURIER_TRACK_SHIPMENT_ENDPOINT: "/track",
  ECOURIER_CANCEL_SHIPMENT_ENDPOINT: ":/cancel-order",
  ECOURIER_CITY_LIST_ENDPOINT: "/city-list",
  ECOURIER_THANA_LIST_ENDPOINT: "/thana-list",
  ECOURIER_AREA_LIST_ENDPOINT: "/area-list",
  ECOURIER_POST_CODE_LIST_ENDPOINT: "/postcode-list",
  ECOURIER_BRANCH_LIST_ENDPOINT: "/branch-list",
  ECOURIER_AREA_BY_DISTRICT_ENDPOINT: "/area-by-district",
  ECOURIER_PAYMENT_STATUS_ENDPOINT: "/payment-status",

  STEADFAST_BASE_URL: "https://portal.steadfast.com.bd/api/v1",
  STEADFAST_API_KEY: "",
  STEADFAST_API_SECRET: "",
  STEADFAST_CREATE_SHIPMENT_ENDPOINT: "/create_order",
  STEADFAST_CREATE_BULK_SHIPMENT_ENDPOINT: "/create_order/bulk-order",
  STEADFAST_TRACK_SHIPMENT_BY_CID_ENDPOINT: "/status_by_cid",
  STEADFAST_TRACK_SHIPMENT_BY_INVOICE_ENDPOINT: "/status_by_invoice",
  STEADFAST_TRACK_SHIPMENT_BY_TRACKING_CODE_ENDPOINT: "/status_by_trackingcode",
  STEADFAST_CHECK_BALANCE_ENDPOINT: "/get_balance",

  PATHAO_TYPE: "pathao",
  ECOURIER_TYPE: "ecourier",
  STEADFAST_TYPE: "steadfast",
};

module.exports = CONFIG;
